server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/library_management_system?useSSL=true&autoReconnect=true&characterEncoding=UTF8&serverTimezone=GMT
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:xml/*.xml
