server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/spring-boot-example?useSSL=true&autoReconnect=true&characterEncoding=UTF8&serverTimezone=GMT
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
        # -----数据库连接池信息-----
        type: com.alibaba.druid.pool.DruidDataSource
        # 初始化时建立物理连接的个数
        initialSize: 3
        # 最小连接池数量
        minIdle: 3
        # 最大连接池数量
        maxActive: 30
        # 获取连接时最大等待时间，单位毫秒
        maxWait: 15000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 120000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 用来检测连接是否有效的sql，要求是一个查询语句。
        # 如果validationQuery为null，testOnBorrow、testOnReturn、
        # testWhileIdle都不会其作用。
        validationQuery: SELECT 1 FROM DUAL
        # 建议配置为true，不影响性能，并且保证安全性。
        # 申请连接的时候检测，如果空闲时间大于
        # timeBetweenEvictionRunsMillis，
        # 执行validationQuery检测连接是否有效。
        testWhileIdle: true
        #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOnBorrow: false
        # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
        testOnReturn: false
        # 是否缓存preparedStatement，也就是PSCache。
        # PSCache对支持游标的数据库性能提升巨大，比如说oracle。
        # 在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
        # 5.5及以上版本有PSCache，建议开启。
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 50
        # -----数据库连接池信息-----

mybatis:
  mapper-locations: classpath*:xml/*.xml
