server:
  port: 8081

spring:
    dubbo:
        application:
            name: consumer
        registry:
            address: zookeeper://127.0.0.1:2181
        scan: org.spring.springboot.dubbo
    datasource:
            name: test
            url: jdbc:mysql://localhost:3306/library_management_system?useSSL=true&autoReconnect=true&characterEncoding=UTF8&serverTimezone=GMT
            username: root
            password:
            driver-class-name: com.mysql.jdbc.Driver